### PR TITLE
Initial PR for my third project

### PR DESCRIPTION
**Pull request by duaneandrea**
- Created a new repository
- Pulled code to the repository
- Modified index.html
- Created a new branch "review code"
- Pushed code to the branch

### CODE REVIEW

**Review by duaneandrea — COMMENTED** [review]
- You need a detailed Readme.md file
- You need to include licence.md
- You forgot to include the linters

**Review by shella12 — CHANGES_REQUESTED** [review]
Hi @duaneandrea, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- used the GitHub inline comments feature ✅ 
- Left at least comments ✅   

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shella12** [comment]
> * You need a detailed Readme.md file
> * You need to include licence.md
> * You forgot to include the linters

Great job on using the inline comment feature and making a useful suggestion to improve the quality of your code. However you can improve your communication using following suggestions 👇 👇 :

1.  Please make sure your comment is phrased politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"_I think it would be better to use semantic tags_"*
* This reads as an order: *"_Use semantic tags_"*

2. Please make sure your comments are clear and easy to understand. For Example:

* This is a clear comment: _"*The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?"*_

* This is a vague comment: _*"The README is not descriptive, why don't you make it better?"*_

3. Please make sure to always include an explanation, a "why", for each requested change. For example:

* This is a well-explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
* This request lacks a "why": *Why don't you use an article tag here instead of a div?*

**Review by duaneandrea — COMMENTED** [review]
- It would be helpful to have a more detailed Readme.md file that includes information about the project, its purpose, and how to run it. This will make it easier for others to understand and use your code. Here is a link to the template that Microverse has created for you you can use that (https://github.com/microverseinc/readme-template)
- It would be great to include a license file such as licence.md in your project. This will help to clarify the terms under which your code can be used and shared. Here is a link to the template of the licence.md file (https://github.com/pagarme/opensource/blob/master/templates/LICENSE.md)
- It would be beneficial to include linters, such as ESLint, in your project to ensure consistency and maintainability of your code. This will help to catch errors and improve the overall quality of your code.

**Review by jerryowusu — APPROVED** [review]
Hi @duaneandrea 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

chelsea-mason-approve


## Highlights
Gave at least two comments :+1: 
Made requested changes :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
